version: '3.8'

services:
  vehicle:
    build:
      context: .
    container_name: sentinel.vehicle
    volumes:
      - ./sentinel.vehicle:/sentinel
    working_dir: /sentinel
    environment:
      - ROS_DOMAIN_ID=0
    networks:
      ros_network:
        ipv4_address: 192.168.1.10
    tty: true

  computer:
    build:
      context: .
    container_name: sentinel.computer
    volumes:
      - ./sentinel.computer:/sentinel
    working_dir: /sentinel
    environment:
      - ROS_DOMAIN_ID=0
    networks:
      ros_network:
        ipv4_address: 192.168.1.20
    tty: true

networks:
  ros_network:
    driver: bridge
    ipam:
      config:
        - subnet: '192.168.1.0/24'
