camera_publisher:
  ros__parameters:
    computer_host: "173.20.10.3"
    computer_port: 9000
    vehicle_host: "0.0.0.0"
    vehicle_port: 8000
    chunk_size: 60000
    camera_width: 640
    camera_height: 480
    camera_fps: 30
    camera_encoding: ".jpg"