<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">


    <!-- =================================================================================== -->
    <!-- |                                    Lidar                                        | -->
    <!-- =================================================================================== -->
    <!-- Lidar !-->
    <link name="lidar">
        <visual>
            <geometry>
                <cylinder radius="0.0295" length="0.026" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="NavyBlue" />
        </visual>
        <collision>
            <geometry>
                <cylinder radius="0.0295" length="0.026" />
            </geometry>
        </collision>
        <xacro:inertial_cylinder mass="0.148" length="0.0295" radius="0.026">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_cylinder>
    </link>

    <!-- Body & Lidar Joint !-->
    <joint name="lidar_joint" type="fixed">
        <parent link="chassis_mid" />
        <child link="lidar" />
        <origin
            xyz="-${chassis_total_length/2 - 0.0295 - 0.045} ${chassis_small_width/2 - 0.0295 - 0.02} ${0.026 *2}"
            rpy="0.0 0.0 0.0" />
    </joint>


    <gazebo reference="lidar">
        <sensor type="gpu_lidar" name="lidar">
            <pose>0 0 0 0 0 0</pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <lidar>
                <scan>
                    <horizontal>
                        <samples>360</samples>
                        <min_angle>-3.14159</min_angle>
                        <max_angle>3.14159</max_angle>
                    </horizontal>
                </scan>
                <range>
                    <min>0.3</min>
                    <max>12</max>
                </range>
            </lidar>
            <topic>scan</topic>
            <gz_frame_id>lidar</gz_frame_id>
        </sensor>
    </gazebo>

</robot>