<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

    <xacro:include filename="inertial_macros.xacro" />

    <!-- =================================================================================== -->
    <!-- |                                   Motors                                        | -->
    <!-- =================================================================================== -->
    <!-- Motor -->
    <xacro:macro name="motors" params="prefix">
        <link name="${prefix}_motor">
            <visual>
                <geometry>
                    <cylinder radius="${motor_radius}" length="${motor_length}" />
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <material name="Gray" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="${motor_radius}" length="${motor_length}" />
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${motor_mass}" length="${motor_length}"
                radius="${motor_radius}">
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            </xacro:inertial_cylinder>
        </link>
    </xacro:macro>

    <xacro:motors prefix="left_front" />
    <xacro:motors prefix="left_rear" />
    <xacro:motors prefix="right_front" />
    <xacro:motors prefix="right_rear" />

    <joint name="left_front_motor_joint" type="fixed">
        <parent link="left_front_wheel" />
        <child link="left_front_motor" />
        <origin xyz="0.0 0.0 -${motor_length/2 + wheel_thickness/2}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="left_rear_motor_joint" type="fixed">
        <parent link="left_rear_wheel" />
        <child link="left_rear_motor" />
        <origin xyz="0.0 0.0 -${motor_length/2 + wheel_thickness/2}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>


    <joint name="right_front_motor_joint" type="fixed">
        <parent link="right_front_wheel" />
        <child link="right_front_motor" />
        <origin xyz="0.0 0.0 -${motor_length/2 + wheel_thickness/2}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>


    <joint name="right_rear_motor_joint" type="fixed">
        <parent link="right_rear_wheel" />
        <child link="right_rear_motor" />
        <origin xyz="0.0 0.0 -${motor_length/2 + wheel_thickness/2}" rpy="0 0 0" />
        <axis xyz="0 0 1" />
    </joint>


    <!-- =================================================================================== -->
    <!-- |                                    Arduino                                      | -->
    <!-- =================================================================================== -->
    <!-- Raspberry -->
    <link name="arduino">
        <visual>
            <geometry>
                <box size="0.082 0.053 0.007" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
        </visual>
        <collision>
            <geometry>
                <box size="0.082 0.053 0.007" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.080" x="0.082" y="0.053" z="0.007">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <!-- Arduino joint-->
    <joint name="arduino_joint" type="fixed">
        <parent link="chassis_bottom" />
        <child link="arduino" />
        <origin
            xyz="-${chassis_total_length/2 - 0.0265 - 0.03} ${chassis_small_width/2 - 0.041 - 0.015} ${0.0035 + chassis_height} "
            rpy="0 0.0 ${pi/2}" />
    </joint>
    <!-- =================================================================================== -->
    <!-- |                                  Battery                                        | -->
    <!-- =================================================================================== -->
    <!-- Battery -->
    <link name="battery">
        <visual>
            <geometry>
                <box size="0.075 0.065 0.035" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="Red" />
        </visual>
        <collision>
            <geometry>
                <box size="0.071 0.065 0.035" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.385" x="0.071" y="0.065" z="0.035">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <!-- Battery Mid Joint!-->
    <joint name="battery_mid_joint" type="fixed">
        <parent link="chassis_bottom" />
        <child link="battery" />
        <origin
            xyz="-${chassis_total_length/2 - 0.0325 - 0.035} -${chassis_small_width/2 - 0.0375 - 0.015} ${0.0175 + chassis_height}"
            rpy="0.0 0.0 ${pi/2}" />
    </joint>


    <!-- =================================================================================== -->
    <!-- |                                  PowerBank                                      | -->
    <!-- =================================================================================== -->
    <!-- PowerBank -->
    <link name="powerbank">
        <visual>
            <geometry>
                <box size="0.143 0.070 0.025" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="White" />
        </visual>
        <collision>
            <geometry>
                <box size="0.143 0.070 0.025" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.395" x="0.143" y="0.070" z="0.025">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>
    <!-- powerbank joint-->
    <joint name="powerbank_joint" type="fixed">
        <parent link="chassis_mid" />
        <child link="powerbank" />
        <origin
            xyz="${chassis_total_length/2 - 0.0715 - 0.025} ${chassis_small_width/2 - 0.035 - 0.015} ${chassis_height + 0.0125}"
            rpy="0.0 0.0 0.0" />
    </joint>

    <!-- =================================================================================== -->
    <!-- |                               Motor Driver                                      | -->
    <!-- =================================================================================== -->
    <!-- Motor Driver -->
    <link name="motor_driver">
        <visual>
            <geometry>
                <box size="0.044 0.044 0.02" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="Red" />
        </visual>
        <collision>
            <geometry>
                <box size="0.044 0.044 0.02" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.024" x="0.044" y="0.044" z="0.02">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <!-- Motor Driver Joint-->
    <joint name="motor_driver_joint" type="fixed">
        <parent link="chassis_bottom" />
        <child link="motor_driver" />
        <origin xyz="0 0 0" rpy="0.0 0.0 0.0" />
        <origin
            xyz="${chassis_total_length/2 - 0.022 - 0.01} -${chassis_big_width/2 - 0.022- 0.05} 0.013"
            rpy="0.0 0.0
        0.0" />
    </joint>


    <!-- =================================================================================== -->
    <!-- |                                  Raspberry                                      | -->
    <!-- =================================================================================== -->
    <!-- Raspberry -->
    <link name="raspberry_pi">
        <visual>
            <geometry>
                <box size="0.095 0.064 0.025" />
            </geometry>
            <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
            <material name="DarkGreen" />
        </visual>
        <collision>
            <geometry>
                <box size="0.095 0.064 0.025" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.140" x="0.095" y="0.064" z="0.025">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>

    <!-- Raspberry joint-->
    <joint name="raspberry_pi_joint" type="fixed">
        <parent link="chassis_bottom" />
        <child link="raspberry_pi" />
        <origin
            xyz="${chassis_total_length/2 - 0.04745 -0.03} ${chassis_small_width/2 - 0.032 - 0.015} ${0.0125 + chassis_height}"
            rpy="0.0 0.0 0.0" />
    </joint>


    <!-- =================================================================================== -->
    <!-- |                               Small Cylinder                                    | -->
    <!-- =================================================================================== -->
    <!-- Small_cylinder Macro !-->
    <xacro:macro
        name="small_cylinder" params="prefix">
        <link name="small_cylinder_${prefix}">
            <visual>
                <geometry>
                    <cylinder radius="0.002" length="${small_cylinder_length}" />
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
                <material name="DarkGold" />
            </visual>
            <collision>
                <geometry>
                    <cylinder radius="0.002" length="${small_cylinder_length}" />
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="0.001" length="${small_cylinder_length}" radius="0.002">
                <origin xyz="0 0 0" rpy="0 0 0" />
            </xacro:inertial_cylinder>
        </link>
    </xacro:macro>

    <xacro:small_cylinder prefix="left_front" />
    <xacro:small_cylinder prefix="right_front" />
    <xacro:small_cylinder prefix="left_rear" />
    <xacro:small_cylinder prefix="right_rear" />

    <joint
        name="small_cylinder_left_front_joint" type="fixed">
        <parent link="chassis_bottom" />
        <child link="small_cylinder_left_front" />
        <origin
            xyz="${chassis_total_length/2 - 0.011} ${chassis_big_width/2 - 0.011} ${small_cylinder_length/2 + chassis_height/2}"
            rpy="0 0.0 0" />
    </joint>

    <joint name="small_cylinder_right_front_joint" type="fixed">
        <parent link="chassis_bottom" />
        <child link="small_cylinder_right_front" />
        <origin
            xyz="${chassis_total_length/2 - 0.011} -${chassis_big_width/2 - 0.011} ${small_cylinder_length/2 + chassis_height/2}"
            rpy="0 0.0 0" />
    </joint>

    <joint name="small_cylinder_left_rear_joint" type="fixed">
        <parent link="chassis_bottom" />
        <child link="small_cylinder_left_rear" />
        <origin
            xyz="-${chassis_total_length/2 - 0.011} ${chassis_big_width/2 - 0.011} ${small_cylinder_length/2 + chassis_height/2}"
            rpy="0 0.0 0" />
    </joint>

    <joint name="small_cylinder_right_rear_joint" type="fixed">
        <parent link="chassis_bottom" />
        <child link="small_cylinder_right_rear" />
        <origin
            xyz="-${chassis_total_length/2 - 0.011} -${chassis_big_width/2 - 0.011} ${small_cylinder_length/2 + chassis_height/2}"
            rpy="0 0.0 0" />
    </joint>


</robot>