<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

    <!-- =================================================================================== -->
    <!-- |                                   Camera                                        | -->
    <!-- =================================================================================== -->

    <!-- Body & Camera Joint !-->
    <joint name="camera_joint" type="fixed">
        <parent link="chassis_mid" />
        <child link="camera_link" />
        <origin xyz="${chassis_total_length/2 - 0.007 - 0.005} 0 ${0.02}" rpy="0 0 0" />
    </joint>

    <!-- Camera !-->
    <link name="camera_link">
        <visual>
            <geometry>
                <box size="0.014 0.04 0.035" />
            </geometry>
            <material name="Red" />
        </visual>
        <collision>
            <geometry>
                <box size="0.014 0.04 0.035" />
            </geometry>
        </collision>
        <xacro:inertial_box mass="0.012" x="0.014" y="0.04" z="0.035">
            <origin xyz="0 0 0" rpy="0 0 0" />
        </xacro:inertial_box>
    </link>


    <joint name="camera_optical_joint" type="fixed">
        <parent link="camera_link" />
        <child link="camera_link_optical" />
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
    </joint>
    <link name="camera_link_optical"></link>

    <joint name="depth_camera_optical_joint" type="fixed">
        <parent link="camera_link" />
        <child link="depth_camera_link_optical" />
        <origin xyz="0 0 0" rpy="${-pi/2} 0 ${-pi/2}" />
    </joint>
    <link name="depth_camera_link_optical"></link>

    <gazebo reference="camera_link">
        <sensor name="camera" type="camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>10</update_rate>
            <camera>
                <camera_info_topic>camera/camera_info</camera_info_topic>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.05</near>
                    <far>100</far>
                </clip>
            </camera>
            <topic>camera/image_raw</topic>
            <gz_frame_id>camera_link_optical</gz_frame_id>
        </sensor>
        <sensor name="depth_camera" type="depth_camera">
            <pose> 0 0 0 0 0 0 </pose>
            <visualize>true</visualize>
            <update_rate>30</update_rate>
            <camera>
                <horizontal_fov>1.089</horizontal_fov>
                <image>
                    <format>R8G8B8</format>
                    <width>640</width>
                    <height>480</height>
                </image>
                <clip>
                    <near>0.01</near>
                    <far>100</far>
                </clip>
            </camera>
            <topic>camera/depth/image_raw</topic>
            <gz_frame_id>depth_camera_link_optical</gz_frame_id>
        </sensor>
    </gazebo>

</robot>