<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">

    <xacro:include filename="inertial_macros.xacro" />

    <material name="NavyBlue">
        <color rgba="0.0 0.0 0.5 1.0" />
    </material>

    <material name="WoodYellow">
        <color rgba="1.0 0.8 0.3 0.8" />
    </material>

    <material name="BlackWheel">
        <color rgba="0.0 0.0 0.0 1.0" />
    </material>

    <material name="Red">
        <color rgba="0.1 0.0 0.0 1.0" />
    </material>

    <material name="White">
        <color rgba="0.9 0.9 0.9 1.0" />
    </material>

    <material name="AbsWhite">
        <color rgba="1 1 1 1.0" />
    </material>

    <material name="Gray">
        <color rgba="0.7 0.7 0.7 1.0" />
    </material>

    <material name="DarkGold">
        <color rgba="0.8 0.6 0.2 1.0" />
    </material>
    <material name="DarkGreen">
        <color rgba="0.0 0.3 0.0 1.0" />
    </material>

    <link name="base_link">

    </link>

    <!-- BASE_FOOTPRINT LINK -->

    <joint name="base_footprint_joint" type="fixed">
        <parent link="base_link" />
        <child link="base_footprint" />
        <origin xyz="0 0 0" rpy="0 0 0" />
    </joint>

    <link name="base_footprint">
    </link>


    <xacro:property name="chassis_total_length" value="0.25" />
    <xacro:property name="chassis_small_length" value="0.032" />
    <xacro:property name="chassis_big_length" value="0.077" />
    <xacro:property name="chassis_small_width" value="0.2" />
    <xacro:property name="chassis_big_width" value="0.248" />
    <xacro:property name="chassis_height" value="0.004" />
    <xacro:property name="chassis_mass" value="0.150" />

    <xacro:property name="wheel_radius" value="0.033" />
    <xacro:property name="wheel_thickness" value="0.026" />
    <xacro:property name="wheel_mass" value="0.05" />
    <xacro:property name="wheel_offset_x" value="0.01" />
    <xacro:property name="wheel_offset_z" value="0.01" />

    <xacro:property name="motor_radius" value="0.0244" />
    <xacro:property name="motor_length" value="0.059" />
    <xacro:property name="motor_mass" value="0.096" />
    <xacro:property name="motor_bracket_offset" value="0.01" />
    <xacro:property name="small_cylinder_length" value="0.0435" />


    <!-- =================================================================================== -->
    <!-- |                                    Chassis                                      | -->
    <!-- =================================================================================== -->

    <!-- Chassis Macro !-->
    <xacro:macro name="chassis" params="postfix">
        <link name="chassis_${postfix}">
            <visual>
                <geometry>
                    <box size="${chassis_small_length} ${chassis_big_width} ${chassis_height}" />
                </geometry>
                <origin
                    xyz="${(chassis_small_length + 0.0015 + chassis_big_length)} 0 0"
                    rpy="0.0 0.0 0.0" />
                <material name="WoodYellow" />
            </visual>
            <visual>
                <geometry>
                    <box size="${chassis_big_length} ${chassis_small_width} ${chassis_height}" />
                </geometry>
                <origin xyz="${chassis_big_length/2+(chassis_small_length+0.003)/2} 0 0"
                    rpy="0.0 0.0 0.0" />
                <material name="WoodYellow" />
            </visual>
            <visual>
                <geometry>
                    <box
                        size="${chassis_small_length + 0.003} ${chassis_big_width} ${chassis_height}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0.0 0.0 0.0" />
                <material name="WoodYellow" />
            </visual>
            <visual>
                <geometry>
                    <box size="${chassis_big_length} ${chassis_small_width} ${chassis_height}" />
                </geometry>
                <origin xyz="-${chassis_big_length/2+(chassis_small_length+0.003)/2} 0 0"
                    rpy="0.0 0.0 0.0" />
                <material name="WoodYellow" />
            </visual>
            <visual>
                <geometry>
                    <box size="${chassis_small_length} ${chassis_big_width} ${chassis_height}" />
                </geometry>
                <origin
                    xyz="-${(chassis_small_length + 0.0015 + chassis_big_length)} 0 0"
                    rpy="0.0 0.0 0.0" />
                <material name="WoodYellow" />
            </visual>

            <collision>
                <geometry>
                    <box size="${chassis_small_length} ${chassis_big_width} ${chassis_height}" />
                </geometry>
                <origin
                    xyz="${(chassis_small_length + 0.0015 + chassis_big_length)} 0 0"
                    rpy="0.0 0.0 0.0" />
            </collision>
            <collision>
                <geometry>
                    <box size="${chassis_big_length} ${chassis_small_width} ${chassis_height}" />
                </geometry>
                <origin xyz="${chassis_big_length/2+(chassis_small_length+0.003)/2} 0 0"
                    rpy="0.0 0.0 0.0" />
            </collision>
            <collision>
                <geometry>
                    <box
                        size="${chassis_small_length + 0.003} ${chassis_big_width} ${chassis_height}" />
                </geometry>
                <origin xyz="0 0 0" rpy="0.0 0.0 0.0" />
            </collision>
            <collision>
                <geometry>
                    <box size="${chassis_big_length} ${chassis_small_width} ${chassis_height}" />
                </geometry>
                <origin xyz="-${chassis_big_length/2+(chassis_small_length+0.003)/2} 0 0"
                    rpy="0.0 0.0 0.0" />
            </collision>
            <collision>
                <geometry>
                    <box size="${chassis_small_length} ${chassis_big_width} ${chassis_height}" />
                </geometry>
                <origin
                    xyz="-${(chassis_small_length + 0.0015 + chassis_big_length)} 0 0"
                    rpy="0.0 0.0 0.0" />
            </collision>


            <xacro:inertial_box mass="${chassis_mass}" x="${chassis_total_length}"
                y="${chassis_big_width}"
                z="${chassis_height}">
                <origin
                    xyz="0 0 ${chassis_height}"
                    rpy="0 0 0" />
            </xacro:inertial_box>
        </link>
    </xacro:macro>

    <!-- Chassis bottom !-->
    <xacro:chassis postfix="bottom" />
    <!-- Chassis mid !-->
    <xacro:chassis postfix="mid" />

    <!-- Chassis bottom !-->
    <joint name="chassis_bottom_joint"
        type="fixed">
        <parent link="base_link" />
        <child link="chassis_bottom" />
        <origin xyz="0 0 ${wheel_radius - wheel_radius + motor_radius + motor_bracket_offset}" />
    </joint>

    <!-- Chassis mid !-->
    <joint
        name="chassis_mid_joint" type="fixed">
        <parent link="chassis_bottom" />
        <child link="chassis_mid" />
        <origin xyz="0.0 0.0 ${small_cylinder_length + chassis_height}" />
    </joint>


</robot>