<?xml version="1.0"?>
<robot xmlns:xacro="http://www.ros.org/wiki/xacro" name="robot">
    <!-- =================================================================================== -->
    <!-- |                                     Wheels                                      | -->
    <!-- =================================================================================== -->
    <xacro:macro name="wheels" params="prefix">
        <link name="${prefix}_wheel">
            <visual>
                <geometry>
                    <cylinder radius="${wheel_radius}" length="${wheel_thickness}" />
                </geometry>
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
                <material name="BlackWheel" />
            </visual>
            <collision>
                <geometry>
                    <!-- <cylinder radius=${wheel_radius}" length="${wheel_thickness}" /> -->
                    <sphere radius="${wheel_radius}" />
                </geometry>
            </collision>
            <xacro:inertial_cylinder mass="${wheel_mass}" length="${wheel_thickness}"
                radius="${wheel_radius}">
                <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
            </xacro:inertial_cylinder>
        </link>
    </xacro:macro>

    <xacro:wheels prefix="left_front" />
    <xacro:wheels prefix="left_rear" />
    <xacro:wheels prefix="right_front" />
    <xacro:wheels prefix="right_rear" />

    <joint name="left_front_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_front_wheel" />
        <origin
            xyz="${chassis_big_length/2+(chassis_small_length+0.003)/2} ${chassis_small_width/2 + 0.015} 0.0"
            rpy="${-pi/2} 0.0 0.0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="left_rear_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="left_rear_wheel" />
        <origin
            xyz="-${chassis_big_length/2+(chassis_small_length+0.003)/2} ${chassis_small_width/2 + 0.015} 0.0"
            rpy="${-pi/2} 0.0 0.0" />
        <axis xyz="0 0 1" />
    </joint>

    <joint name="right_front_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_front_wheel" />
        <origin
            xyz="${chassis_big_length/2+(chassis_small_length+0.003)/2} -${chassis_small_width/2 + 0.015} 0.0"
            rpy="${pi/2} 0.0 0.0" />
        <axis xyz="0 0 -1" />
    </joint>

    <joint name="right_rear_wheel_joint" type="continuous">
        <parent link="base_link" />
        <child link="right_rear_wheel" />
        <origin
            xyz="-${chassis_big_length/2+(chassis_small_length+0.003)/2} -${chassis_small_width/2 + 0.015} 0.0"
            rpy="${pi/2} 0.0 0.0" />
        <axis xyz="0 0 -1" />
    </joint>


</robot>